---
title: "US Senate Polls"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(knitr)
library(formattable)
library(tidyverse)

setwd('/Users/john/Documents/polling-errors/predictors_of_polling_errors/')
df_polls <- read_csv("data/senate/senate_polls_merged_refactored.csv")
df_results <- read_csv("data/senate/senate_results_phil.csv")

# merge data
data_senate <- merge(df_polls, df_results, by = c('election_year', 'state'), all.x = T )


# fix gender / race data
data_senate <- data_senate %>%
  mutate(clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Alan Schlesinger', 'white'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Dan Bongino', 'hispanic'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Jim Huffman', 'white'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Linda Smith', 'white'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Lou Barletta', 'white'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Philip Giordano', 'white'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Rick Lazio', 'white'),
         clarifai_race_rep = replace(clarifai_race_rep, clarifai_race_rep == 'Robert Lorge', 'hispanic')) %>%
  as.data.frame()

data_senate <- data_senate %>%
  mutate(clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Barbara Boxer', 'white'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Bob Menendez', 'white'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Catherine Cortez Masto', 'white'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Harold Ford Jr.', 'black'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Ken Salazar', 'white'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Paul Hodes', 'white'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Rick Noriega', 'white'),
         clarifai_race_dem = replace(clarifai_race_dem, clarifai_race_dem == 'Sam Granato', 'white')) %>%
  as.data.frame()

data_senate <- data_senate %>%
  mutate(clarifai_gender_dem = replace(clarifai_gender_dem, clarifai_gender_dem == 'Misty K. Snow', 'feminine'),
         clarifai_gender_rep = replace(clarifai_gender_rep, clarifai_gender_rep == 'Slade Gorton', 'masculine')) %>%
  as.data.frame()


# compute days until election, gender and race dummy, incumbency dummy, two-party vote share
data_senate <- data_senate %>%
  mutate(gender_rep_dummy = if_else(clarifai_gender_rep == 'feminine', 1, 0),
         gender_dem_dummy = if_else(clarifai_gender_dem == 'feminine', 1, 0),
         race_rep_dummy = if_else(clarifai_race_rep != 'white', 1, 0),
         race_dem_dummy = if_else(clarifai_race_dem != 'white', 1, 0),
         state_year = paste0(election_year, '_', state),
         rep_poll2 = rep_vote/(rep_vote + dem_vote)
  )


# Subset complete cases
data_senate <- data_senate %>% 
  subset(!is.na(gender_rep_dummy) &
           !is.na(gender_dem_dummy) &
           !is.na(race_rep_dummy) &
           !is.na(race_dem_dummy) &
           !is.na(rep_poll2) &
           !is.na(rep_result2) &
           !is.na(n))

df <- data_senate %>% 
  select(election_year, state, rep_result2, rep_poll2, # rep_poll2_av, bias, region_group4
         gender_rep_dummy, gender_dem_dummy, race_rep_dummy, race_dem_dummy)

# aggregate
df <- df %>% 
  group_by(election_year, state) %>% 
  summarise(rep_poll2_av = mean(rep_poll2, na.rm = T),
            rep_result2 = mean(rep_result2, na.rm = T),
            gender_rep = mean(gender_rep_dummy, na.rm = T), 
            gender_dem= mean(gender_dem_dummy, na.rm = T), 
            race_rep = mean(race_rep_dummy, na.rm = T), 
            race_dem = mean(race_dem_dummy, na.rm = T),
            n_polls = n())

# Add groups (source: https://en.wikipedia.org/wiki/United_States_Census_Bureau)
df <- df %>%
  mutate(region_group4 = case_when(state == 'CT'|
                                     state == 'ME'|
                                     state == 'MA'|
                                     state == 'NH'|
                                     state == 'NJ'|
                                     state == 'NY'|
                                     state == 'PA'|
                                     state == 'RI'|
                                     state == 'VT' ~ 'Northeast',
                                   state == 'IL'|
                                     state == 'IN'|
                                     state == 'IA'|
                                     state == 'KS'|
                                     state == 'MI'|
                                     state == 'MN'|
                                     state == 'MO'|
                                     state == 'NE'|
                                     state == 'ND'|
                                     state == 'OH'|
                                     state == 'SD'|
                                     state == 'WI' ~ 'Midwest',
                                   state == 'AL'|
                                     state == 'AR'|
                                     state == 'DE'|
                                     state == 'FL'|
                                     state == 'GA'|
                                     state == 'KY'|
                                     state == 'LA'|
                                     state == 'MD'|
                                     state == 'MS'|
                                     state == 'NC'|
                                     state == 'OK'|
                                     state == 'SC'|
                                     state == 'TN'|
                                     state == 'TX'|
                                     state == 'VA'|
                                     state == 'WV' ~ 'South',
                                   state == 'AZ'|
                                     state == 'AK'|
                                     state == 'CA'|
                                     state == 'CO'|
                                     state == 'HI'|
                                     state == 'ID'|
                                     state == 'MT'|
                                     state == 'NV'|
                                     state == 'NM'|
                                     state == 'UT'|
                                     state == 'OR'|
                                     state == 'WA'|
                                     state == 'WY' ~ 'West'))

df$bias <- round(df$rep_poll2_av - df$rep_result2, digits = 2)

df <- df %>% 
  select(election_year, state, region_group4, rep_result2, rep_poll2_av, bias, 
         gender_rep, gender_dem, race_rep, race_dem, n_polls)
```

Overview by Election:

```{r table, echo=FALSE}
# formattable(df)

color_tile2 <- function (...) {
  formatter("span", style = function(x) {
    style(display = "block",
          padding = "0 4px", 
          `border-radius` = "4px", 
          `background-color` = csscolor(matrix(as.integer(colorRamp(...)(normalize(as.numeric(x)))), 
                                               byrow=TRUE, dimnames=list(c("red","green","blue"), NULL), nrow=3)))
  })}

formattable(df, list(
  bias = color_tile2(c("red", "white", "green")),
  gender_rep = color_tile("white", "cornflowerblue"),
  gender_dem = color_tile("white", "cornflowerblue"),
  race_rep = color_tile("white", "cornflowerblue"),
  race_dem = color_tile("white", "cornflowerblue")
  )
)
```
