########################################################################################
# Process script: Convert html to txt for senate polls from 1998 to 2018 
# Author: Sina Chen
# Source: www.pollingreport.com 
#
########################################################################################

#### Libraries ####

library(XML)
library(stringr)
library(xml2)
library(rvest)
library(dplyr)
library(readr)
library(tidyr)
library(tibble)

#### Directory ####

scr_dir <- 'your working directory'

#### 1998 ####

# read html
setwd(paste0(scr_dir,'/year1998/html'))
files1998 <- dir(paste0(scr_dir,'/year1998/html'))
states1998 <- sapply(files1998, htmlParse)

{
  pres_tables_al_ct <- xpathSApply(doc = states1998$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl_ia <- xpathSApply(doc = states1998$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ks_la <- xpathSApply(doc = states1998$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_md_mt <- xpathSApply(doc = states1998$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne_nd <- xpathSApply(doc = states1998$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh_wi <- xpathSApply(doc = states1998$`6.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year1998/txt'))
{
  sink("Alabama_Colorado1998.txt")
  print(pres_tables_al_ct)
  sink()
  sink("Florida_Iowa1998.txt")
  print(pres_tables_fl_ia)
  sink()
  sink("Kansas_Louisiana1998.txt")
  print(pres_tables_ks_la)
  sink()
  sink("Maryland_Montana1998.txt")
  print(pres_tables_md_mt)
  sink()
  sink("Nebraska_NorthDakota1998.txt")
  print(pres_tables_ne_nd)
  sink()
  sink("Ohio_Wisconsin1998.txt")
  print(pres_tables_oh_wi)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2000 ####

# read html
setwd(paste0(scr_dir,'/year2000/html'))

files2000 <- dir(paste0(scr_dir,'/year2000/html'))
states2000 <- sapply(files2000, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2000$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ar <- xpathSApply(doc = states2000$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ak <- xpathSApply(doc = states2000$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2000$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co <- xpathSApply(doc = states2000$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ct <- xpathSApply(doc = states2000$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_de <- xpathSApply(doc = states2000$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2000$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ge <- xpathSApply(doc = states2000$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ha <- xpathSApply(doc = states2000$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_id <- xpathSApply(doc = states2000$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_il <- xpathSApply(doc = states2000$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_in <- xpathSApply(doc = states2000$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_io <- xpathSApply(doc = states2000$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ka <- xpathSApply(doc = states2000$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ke <- xpathSApply(doc = states2000$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_lo <- xpathSApply(doc = states2000$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me <- xpathSApply(doc = states2000$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_md <- xpathSApply(doc = states2000$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ma <- xpathSApply(doc = states2000$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi <- xpathSApply(doc = states2000$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mn <- xpathSApply(doc = states2000$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ms <- xpathSApply(doc = states2000$`23.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mo <- xpathSApply(doc = states2000$`24.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mt <- xpathSApply(doc = states2000$`25.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne <- xpathSApply(doc = states2000$`26.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nv <- xpathSApply(doc = states2000$`27.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh <- xpathSApply(doc = states2000$`28.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj <- xpathSApply(doc = states2000$`29.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nm <- xpathSApply(doc = states2000$`30.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2000$`31.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc <- xpathSApply(doc = states2000$`32.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nd <- xpathSApply(doc = states2000$`33.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh <- xpathSApply(doc = states2000$`34.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ok <- xpathSApply(doc = states2000$`35.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_or <- xpathSApply(doc = states2000$`36.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pe <- xpathSApply(doc = states2000$`37.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri <- xpathSApply(doc = states2000$`38.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sc <- xpathSApply(doc = states2000$`39.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_te <- xpathSApply(doc = states2000$`40.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tex <- xpathSApply(doc = states2000$`41.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ut <- xpathSApply(doc = states2000$`42.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ve <- xpathSApply(doc = states2000$`43.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_vi <- xpathSApply(doc = states2000$`44.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa <- xpathSApply(doc = states2000$`45.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wv <- xpathSApply(doc = states2000$`46.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi <- xpathSApply(doc = states2000$`47.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wy <- xpathSApply(doc = states2000$`48.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2000/txt'))

{
  sink("Alabama2000.txt")
  print(pres_tables_al)
  sink()
  sink("Arizona2000.txt")
  print(pres_tables_ar)
  sink()
  sink("Arkansas2000.txt")
  print(pres_tables_ak)
  sink()
  sink("California2000.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2000.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2000.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2000.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2000.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2000.txt")
  print(pres_tables_ge)
  sink()
  sink("Hawaii2000.txt")
  print(pres_tables_ha)
  sink()
  sink("Idaho2000.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2000.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2000.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2000.txt")
  print(pres_tables_io)
  sink()
  sink("Kansas2000.txt")
  print(pres_tables_ka)
  sink()
  sink("Kentucky2000.txt")
  print(pres_tables_ke)
  sink()
  sink("Louisiana2000.txt")
  print(pres_tables_lo)
  sink()
  sink("Maine2000.txt")
  print(pres_tables_ma)
  sink()
  sink("Maryland2000.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2000.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2000.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2000.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2000.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2000.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2000.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2000.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2000.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2000.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2000.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2000.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2000.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2000.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2000.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2000.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2000.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2000.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2000.txt")
  print(pres_tables_pe)
  sink()
  sink("RhodeIsland2000.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2000.txt")
  print(pres_tables_sc)
  sink()
  sink("Tennessee2000.txt")
  print(pres_tables_te)
  sink()
  sink("Texas2000.txt")
  print(pres_tables_tex)
  sink()
  sink("Utah2000.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2000.txt")
  print(pres_tables_ve)
  sink()
  sink("Virginia2000.txt")
  print(pres_tables_vi)
  sink()
  sink("Washington2000.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2000.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2000.txt")
  print(pres_tables_wi)
  sink()
  sink("Wyoming2000.txt")
  print(pres_tables_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2002 ####

# read html
setwd(paste0(scr_dir,'/year2002/html'))

files2002 <- dir(paste0(scr_dir,'/year2002/html'))
states2002 <- sapply(files2002, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2002$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ak <- xpathSApply(doc = states2002$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_az <- xpathSApply(doc = states2002$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ar <- xpathSApply(doc = states2002$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2002$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co <- xpathSApply(doc = states2002$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ct <- xpathSApply(doc = states2002$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2002$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ga <- xpathSApply(doc = states2002$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_hi <- xpathSApply(doc = states2002$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_id <- xpathSApply(doc = states2002$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_il <- xpathSApply(doc = states2002$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_in <- xpathSApply(doc = states2002$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia <- xpathSApply(doc = states2002$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ks <- xpathSApply(doc = states2002$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ky <- xpathSApply(doc = states2002$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_la <- xpathSApply(doc = states2002$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me <- xpathSApply(doc = states2002$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_md <- xpathSApply(doc = states2002$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ma <- xpathSApply(doc = states2002$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi <- xpathSApply(doc = states2002$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mn <- xpathSApply(doc = states2002$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mo <- xpathSApply(doc = states2002$`23.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mt <- xpathSApply(doc = states2002$`24.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne <- xpathSApply(doc = states2002$`25.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nv <- xpathSApply(doc = states2002$`26.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh <- xpathSApply(doc = states2002$`27.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj <- xpathSApply(doc = states2002$`28.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nm <- xpathSApply(doc = states2002$`29.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2002$`30.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc <- xpathSApply(doc = states2002$`31.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nd <- xpathSApply(doc = states2002$`32.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh <- xpathSApply(doc = states2002$`33.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ok <- xpathSApply(doc = states2002$`34.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_or <- xpathSApply(doc = states2002$`35.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2002$`36.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri <- xpathSApply(doc = states2002$`37.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sc <- xpathSApply(doc = states2002$`38.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sd <- xpathSApply(doc = states2002$`39.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tn <- xpathSApply(doc = states2002$`40.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tx <- xpathSApply(doc = states2002$`41.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ut <- xpathSApply(doc = states2002$`42.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_vt <- xpathSApply(doc = states2002$`43.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa <- xpathSApply(doc = states2002$`44.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wv <- xpathSApply(doc = states2002$`45.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi <- xpathSApply(doc = states2002$`46.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wy <- xpathSApply(doc = states2002$`47.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2002/txt'))

{
  sink("Alabama2002.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska2002.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2002.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2002.txt")
  print(pres_tables_ar)
  sink()
  sink("California2002.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2002.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2002.txt")
  print(pres_tables_ct)
  sink()
  sink("Florida2002.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2002.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii2002.txt")
  print(pres_tables_hi)
  sink()
  sink("Idaho2002.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2002.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2002.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2002.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas2002.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2002.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2002.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2002.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2002.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2002.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2002.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2002.txt")
  print(pres_tables_mn)
  sink()
  sink("Missouri2002.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2002.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2002.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2002.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2002.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2002.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2002.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2002.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2002.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2002.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2002.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2002.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2002.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2002.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2002.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2002.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2002.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2002.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2002.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2002.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2002.txt")
  print(pres_tables_vt)
  sink()
  sink("Washington2002.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2002.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2002.txt")
  print(pres_tables_wi)
  sink()
  sink("Wyoming2002.txt")
  print(pres_tables_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2004 ####

# read html
setwd(paste0(scr_dir,'/year2004/html'))

files2004 <- dir(paste0(scr_dir,'/year2004/html'))
states2004 <- sapply(files2004, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2004$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ak <- xpathSApply(doc = states2004$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_az <- xpathSApply(doc = states2004$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ar <- xpathSApply(doc = states2004$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2004$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co <- xpathSApply(doc = states2004$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ct <- xpathSApply(doc = states2004$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_de <- xpathSApply(doc = states2004$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_dc <- xpathSApply(doc = states2004$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2004$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ga <- xpathSApply(doc = states2004$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_hi <- xpathSApply(doc = states2004$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_id <- xpathSApply(doc = states2004$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_il <- xpathSApply(doc = states2004$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_in <- xpathSApply(doc = states2004$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia <- xpathSApply(doc = states2004$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ks <- xpathSApply(doc = states2004$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ky <- xpathSApply(doc = states2004$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_la <- xpathSApply(doc = states2004$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me <- xpathSApply(doc = states2004$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_md <- xpathSApply(doc = states2004$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ma <- xpathSApply(doc = states2004$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi <- xpathSApply(doc = states2004$`23.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mn <- xpathSApply(doc = states2004$`24.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ms <- xpathSApply(doc = states2004$`25.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mo <- xpathSApply(doc = states2004$`26.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mt <- xpathSApply(doc = states2004$`27.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne <- xpathSApply(doc = states2004$`28.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nv <- xpathSApply(doc = states2004$`29.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh <- xpathSApply(doc = states2004$`30.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj <- xpathSApply(doc = states2004$`31.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nm <- xpathSApply(doc = states2004$`32.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2004$`33.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc <- xpathSApply(doc = states2004$`34.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nd <- xpathSApply(doc = states2004$`35.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh <- xpathSApply(doc = states2004$`36.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ok <- xpathSApply(doc = states2004$`37.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_or <- xpathSApply(doc = states2004$`38.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2004$`39.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri <- xpathSApply(doc = states2004$`40.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sc <- xpathSApply(doc = states2004$`41.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sd <- xpathSApply(doc = states2004$`42.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tn <- xpathSApply(doc = states2004$`43.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tx <- xpathSApply(doc = states2004$`44.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ut <- xpathSApply(doc = states2004$`45.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_vt <- xpathSApply(doc = states2004$`46.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_va <- xpathSApply(doc = states2004$`47.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa <- xpathSApply(doc = states2004$`48.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wv <- xpathSApply(doc = states2004$`49.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi <- xpathSApply(doc = states2004$`50.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2004/txt'))

{
  sink("Alabama2004.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska2004.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2004.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2004.txt")
  print(pres_tables_ar)
  sink()
  sink("California2004.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2004.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2004.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2004.txt")
  print(pres_tables_de)
  sink()
  sink("DistrictOfColumbia2004.txt")
  print(pres_tables_dc)
  sink()
  sink("Florida2004.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2004.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii2004.txt")
  print(pres_tables_hi)
  sink()
  sink("Idaho2004.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2004.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2004.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2004.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas2004.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2004.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2004.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2004.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2004.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2004.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2004.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2004.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2004.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2004.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2004.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2004.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2004.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2004.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2004.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2004.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2004.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2004.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2004.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2004.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2004.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2004.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2004.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2004.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2004.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2004.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2004.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2004.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2004.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2004.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2004.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2004.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2004.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2004.txt")
  print(pres_tables_wi)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2006 ####

# read html
setwd(paste0(scr_dir,'/year2006/html'))

files2006 <- dir(paste0(scr_dir,'/year2006/html'))
states2006 <- sapply(files2006, htmlParse)

{
  pres_tables_al_ar <- xpathSApply(doc = states2006$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2006$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co <- xpathSApply(doc = states2006$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ct <- xpathSApply(doc = states2006$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_de <- xpathSApply(doc = states2006$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2006$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ga_hi <- xpathSApply(doc = states2006$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_id <- xpathSApply(doc = states2006$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_il <- xpathSApply(doc = states2006$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_in_ia <- xpathSApply(doc = states2006$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ks_me <- xpathSApply(doc = states2006$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_md <- xpathSApply(doc = states2006$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ma <- xpathSApply(doc = states2006$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi <- xpathSApply(doc = states2006$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mn_mt <- xpathSApply(doc = states2006$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne_nh <- xpathSApply(doc = states2006$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj_nm <- xpathSApply(doc = states2006$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2006$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc_nd <- xpathSApply(doc = states2006$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh <- xpathSApply(doc = states2006$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ok_or <- xpathSApply(doc = states2006$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2006$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri_sc <- xpathSApply(doc = states2006$`23.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sd_tn <- xpathSApply(doc = states2006$`24.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tx <- xpathSApply(doc = states2006$`25.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ut_va <- xpathSApply(doc = states2006$`26.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa_wv <- xpathSApply(doc = states2006$`27.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi_wy <- xpathSApply(doc = states2006$`28.html`, path ="//table[@dir='ltr']//child::table")
}


# write txt
setwd(paste0(scr_dir,'/year2006/txt'))

{
  sink("Alabama_Arkansas2006.txt")
  print(pres_tables_al_ar)
  sink()
  sink("California2006.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2006.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2006.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2006.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2006.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia_Hawaii2006.txt")
  print(pres_tables_ga_hi)
  sink()
  sink("Idaho2006.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2006.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana_Iowa2006.txt")
  print(pres_tables_in_ia)
  sink()
  sink("Kansas_Maine2006.txt")
  print(pres_tables_ks_me)
  sink()
  sink("Maryland2006.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2006.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2006.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota_Montana2006.txt")
  print(pres_tables_mn_mt)
  sink()
  sink("Nebraska_NewHampshire2006.txt")
  print(pres_tables_ne_nh)
  sink()
  sink("NewJersey_NewMexico2006.txt")
  print(pres_tables_nj_nm)
  sink()
  sink("NewYork2006.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina_NorthDakota2006.txt")
  print(pres_tables_nc_nd)
  sink()
  sink("Ohio2006.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma_Oregon2006.txt")
  print(pres_tables_ok_or)
  sink()
  sink("Pennsylvania2006.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland_southCarolina2006.txt")
  print(pres_tables_ri_sc)
  sink()
  sink("SouthDakota_Tennessee2006.txt")
  print(pres_tables_sd_tn)
  sink()
  sink("Texas2006.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah_Virginia2006.txt")
  print(pres_tables_ut_va)
  sink()
  sink("Washington_WestVirginia2006.txt")
  print(pres_tables_wa_wv)
  sink()
  sink("Wisconsin_Wyoming2006.txt")
  print(pres_tables_wi_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2008 ####

# read html
setwd(paste0(scr_dir,'/year2008/html'))

files2008 <- dir(paste0(scr_dir,'/year2008/html'))
states2008 <- sapply(files2008, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2008$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ak_ar <- xpathSApply(doc = states2008$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2008$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co_de <- xpathSApply(doc = states2008$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2008$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ga <- xpathSApply(doc = states2008$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_hi_in <- xpathSApply(doc = states2008$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia <- xpathSApply(doc = states2008$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ks_ky <- xpathSApply(doc = states2008$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_la <- xpathSApply(doc = states2008$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me_ma <- xpathSApply(doc = states2008$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi <- xpathSApply(doc = states2008$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mn <- xpathSApply(doc = states2008$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ms_mt <- xpathSApply(doc = states2008$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne_nv <- xpathSApply(doc = states2008$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh <- xpathSApply(doc = states2008$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj <- xpathSApply(doc = states2008$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nm <- xpathSApply(doc = states2008$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2008$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc <- xpathSApply(doc = states2008$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nd <- xpathSApply(doc = states2008$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh <- xpathSApply(doc = states2008$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ok_or <- xpathSApply(doc = states2008$`23.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2008$`24.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri <- xpathSApply(doc = states2008$`25.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_sc_sd <- xpathSApply(doc = states2008$`26.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tn <- xpathSApply(doc = states2008$`27.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tx <- xpathSApply(doc = states2008$`28.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ut_va <- xpathSApply(doc = states2008$`29.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa_wv <- xpathSApply(doc = states2008$`30.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi_wy <- xpathSApply(doc = states2008$`31.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2008/txt'))

{
  sink("Alabama.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska_Arkansas2008.txt")
  print(pres_tables_ak_ar)
  sink()
  sink("California2008.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado_Delaware2008.txt")
  print(pres_tables_co_de)
  sink()
  sink("Florida2008.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2008.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii_Indiana2008.txt")
  print(pres_tables_hi_in)
  sink()
  sink("Iowa2008.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas_Kentucky2008.txt")
  print(pres_tables_ks_ky)
  sink()
  sink("Louisiana2008.txt")
  print(pres_tables_la)
  sink()
  sink("Main_Massachusetts2008.txt")
  print(pres_tables_me_ma)
  sink()
  sink("Michigan2008.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2008.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi_Montana2008.txt")
  print(pres_tables_ms_mt)
  sink()
  sink("Nebraska_Nevada2008.txt")
  print(pres_tables_ne_nv)
  sink()
  sink("NewHampshire2008.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2008.txt")
  print(pres_tables_nj)
  sink()
  sink("NewHampshire2008.txt")
  print(pres_tables_nh)
  sink()
  sink("NewMexico2008.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2008.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2008.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2008.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2008.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma_Oregon2008.txt")
  print(pres_tables_ok_or)
  sink()
  sink("Pennsylvania2008.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2008.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina_SouthDakota2008.txt")
  print(pres_tables_sc_sd)
  sink()  
  sink("Tennessee2008.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2008.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah_Virginia2008.txt")
  print(pres_tables_ut_va)
  sink()
  sink("Washington_WestVirginia2008.txt")
  print(pres_tables_wa_wv)
  sink()
  sink("Wisconsin_Wyoming2008.txt")
  print(pres_tables_wi_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2010 ####

# read html
setwd(paste0(scr_dir,'/year2010/html'))

files2010 <- dir(paste0(scr_dir,'/year2010/html'))
states2010 <- sapply(files2010, htmlParse)

{
  pres_tables_al_ak <- xpathSApply(doc = states2010$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_az <- xpathSApply(doc = states2010$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ar <- xpathSApply(doc = states2010$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2010$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co <- xpathSApply(doc = states2010$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ct_de <- xpathSApply(doc = states2010$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2010$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ga <- xpathSApply(doc = states2010$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_hi_in <- xpathSApply(doc = states2010$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia_la <- xpathSApply(doc = states2010$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me_ma <- xpathSApply(doc = states2010$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi <- xpathSApply(doc = states2010$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mn_mt <- xpathSApply(doc = states2010$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne_nv <- xpathSApply(doc = states2010$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh_nm <- xpathSApply(doc = states2010$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2010$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc_nd <- xpathSApply(doc = states2010$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh <- xpathSApply(doc = states2010$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ok_or <- xpathSApply(doc = states2010$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2010$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri_ut <- xpathSApply(doc = states2010$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_vt_wv <- xpathSApply(doc = states2010$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi_wy <- xpathSApply(doc = states2010$`23.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2010/txt'))

{
  sink("Alabama_Alaska.txt")
  print(pres_tables_al_ak)
  sink()
  sink("Arizona2010.txt")
  print(pres_tables_az)
  sink()  
  sink("Arkansas2010.txt")
  print(pres_tables_ar)
  sink()
  sink("California2010.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2010.txt")
  print(pres_tables_co)
  sink()  
  sink("Connecticut_Delaware2010.txt")
  print(pres_tables_ct_de)
  sink()
  sink("Florida2010.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2010.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii_Indiana2010.txt")
  print(pres_tables_hi_in)
  sink()
  sink("Iowa_Louisiana2010.txt")
  print(pres_tables_ia_la)
  sink()
  sink("Main_Massachusetts2010.txt")
  print(pres_tables_me_ma)
  sink()
  sink("Michigan2010.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota_Montana20102010.txt")
  print(pres_tables_mn_mt)
  sink()
  sink("Nebraska_Nevada2010.txt")
  print(pres_tables_ne_nv)
  sink()
  sink("NewHampshire_NewMexico2010.txt")
  print(pres_tables_nh_nm)
  sink()
  sink("NewYork2010.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina_NorthDakota2010.txt")
  print(pres_tables_nc_nd)
  sink()
  sink("Ohio2010.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma_Oregon2010.txt")
  print(pres_tables_ok_or)
  sink()
  sink("Pennsylvania2010.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland_Utah2010.txt")
  print(pres_tables_ri_ut)
  sink()
  sink("Vermont_WestVirginia2010.txt")
  print(pres_tables_vt_wv)
  sink()
  sink("Wisconsin_Wyoming2010.txt")
  print(pres_tables_wi_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2012 ####

# read html
setwd(paste0(scr_dir,'/year2012/html'))

files2012 <- dir(paste0(scr_dir,'/year2012/html'))
states2012 <- sapply(files2012, htmlParse)

{
  pres_tables_al_ar <- xpathSApply(doc = states2012$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2012$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co_de <- xpathSApply(doc = states2012$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl <- xpathSApply(doc = states2012$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ga_in <- xpathSApply(doc = states2012$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia_la <- xpathSApply(doc = states2012$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me_md <- xpathSApply(doc = states2012$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ma <- xpathSApply(doc = states2012$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi_mn <- xpathSApply(doc = states2012$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ms_ne <- xpathSApply(doc = states2012$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nv <- xpathSApply(doc = states2012$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh <- xpathSApply(doc = states2012$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj_nm <- xpathSApply(doc = states2012$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2012$`14.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc_nd <- xpathSApply(doc = states2012$`15.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh_or <- xpathSApply(doc = states2012$`16.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2012$`17.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri_sd <- xpathSApply(doc = states2012$`18.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_tn_tx <- xpathSApply(doc = states2012$`19.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ut_vt <- xpathSApply(doc = states2012$`20.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_va <- xpathSApply(doc = states2012$`21.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa_wv <- xpathSApply(doc = states2012$`22.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wi_wy <- xpathSApply(doc = states2012$`23.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2012/txt'))

{
  sink("Alabama_Arkansas.txt")
  print(pres_tables_al_ar)
  sink()
  sink("California2012.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado_Delaware2012.txt")
  print(pres_tables_co_de)
  sink()  
  sink("Florida2012.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia_Indiana2012.txt")
  print(pres_tables_ga_in)
  sink()
  sink("Iowa_Louisiana2012.txt")
  print(pres_tables_ia_la)
  sink()
  sink("Main_Maaryland2012.txt")
  print(pres_tables_me_md)
  sink()
  sink("Massachusetts2012.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan_Minnesota2012.txt")
  print(pres_tables_mi_mn)
  sink()
  sink("Mississippi_Nebraska2012.txt")
  print(pres_tables_ms_ne)
  sink()
  sink("Nevada2012.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2012.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey_NewMexico2012.txt")
  print(pres_tables_nj_nm)
  sink()
  sink("NewYork2012.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina_NorthDakota2012.txt")
  print(pres_tables_nc_nd)
  sink()
  sink("Ohio_Oregon2012.txt")
  print(pres_tables_oh_or)
  sink()
  sink("Pennsylvania2012.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland_SouthDakota2012.txt")
  print(pres_tables_ri_sd)
  sink()
  sink("Tennessee_Texas2012.txt")
  print(pres_tables_tn_tx)
  sink()
  sink("Utah_Vermont2012.txt")
  print(pres_tables_ut_vt)
  sink()
  sink("Virginia2012.txt")
  print(pres_tables_va)
  sink()
  sink("Washington_WestVirginia2012.txt")
  print(pres_tables_wa_wv)
  sink()
  sink("Wisconsin_Wyoming2012.txt")
  print(pres_tables_wi_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))

#### 2014 ####

# read html
setwd(paste0(scr_dir,'/year2014/html'))

files2014 <- dir(paste0(scr_dir,'/year2014/html'))
states2014 <- sapply(files2014, htmlParse)

{
  pres_tables_ak_ar <- xpathSApply(doc = states2014$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ca <- xpathSApply(doc = states2014$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_co_de <- xpathSApply(doc = states2014$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl_il <- xpathSApply(doc = states2014$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia_la <- xpathSApply(doc = states2014$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me_md <- xpathSApply(doc = states2014$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ma <- xpathSApply(doc = states2014$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_mi_mt <- xpathSApply(doc = states2014$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ne_nh <- xpathSApply(doc = states2014$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nj_nm <- xpathSApply(doc = states2014$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny <- xpathSApply(doc = states2014$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nc_or <- xpathSApply(doc = states2014$`12.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2014$`13.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri_wy <- xpathSApply(doc = states2014$`14.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2014/txt'))

{
  sink("Alaska_Arkansas.txt")
  print(pres_tables_ak_ar)
  sink()
  sink("California2014.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado_Delaware2014.txt")
  print(pres_tables_co_de)
  sink()  
  sink("Florida_Illinois2014.txt")
  print(pres_tables_fl_il)
  sink()
  sink("Iowa_Louisiana2014.txt")
  print(pres_tables_ia_la)
  sink()
  sink("Main_Maryland2014.txt")
  print(pres_tables_me_md)
  sink()
  sink("Massachusetts2014.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan_Montana2014.txt")
  print(pres_tables_mi_mt)
  sink()
  sink("Nebraska_NewHampshire2014.txt")
  print(pres_tables_ne_nh)
  sink()
  sink("NewJersey_NewMexico2014.txt")
  print(pres_tables_nj_nm)
  sink()
  sink("NewYork2014.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina_Oregon2014.txt")
  print(pres_tables_nc_or)
  sink()
  sink("Pennsylvania2014.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland_Wyoming2014.txt")
  print(pres_tables_ri_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2016 ####

# read html
setwd(paste0(scr_dir,'/year2016/html'))

files2016 <- dir(paste0(scr_dir,'/year2016/html'))
states2016 <- sapply(files2016, htmlParse)

{
  pres_tables_al_co <- xpathSApply(doc = states2016$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ct_de <- xpathSApply(doc = states2016$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl_ga <- xpathSApply(doc = states2016$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_il_in <- xpathSApply(doc = states2016$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ia <- xpathSApply(doc = states2016$`5.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ks_nv <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nh_nm <- xpathSApply(doc = states2016$`7.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ny_nd <- xpathSApply(doc = states2016$`8.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_oh_or <- xpathSApply(doc = states2016$`9.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa <- xpathSApply(doc = states2016$`10.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_ri_va <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_wa_wy <- xpathSApply(doc = states2016$`12.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2016/txt'))

{
  sink("Alabama_Colorado")
  print(pres_tables_al_co)
  sink()
  sink("Connecticut_Delaware2016.txt")
  print(pres_tables_ct_de)
  sink()
  sink("Florida_Georgia2016.txt")
  print(pres_tables_fl_ga)
  sink()  
  sink("Illinois_Indiana2016.txt")
  print(pres_tables_il_in)
  sink()
  sink("Iowa2016.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas_Nevada2016.txt")
  print(pres_tables_ks_nv)
  sink()
  sink("NewHampshire_NewMexico2016.txt")
  print(pres_tables_nh_nm)
  sink()
  sink("NewYork_NorthDakota2016.txt")
  print(pres_tables_ny_nd)
  sink()
  sink("Ohio_Oregon2016.txt")
  print(pres_tables_oh_or)
  sink()
  sink("Pennsylvania2016.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland_Virginia2016.txt")
  print(pres_tables_ri_va)
  sink()
  sink("Washingtom_Wyoming2016.txt")
  print(pres_tables_wa_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


#### 2018 ####

# read html
setwd(paste0(scr_dir,'/year2018/html'))

files2018 <- dir(paste0(scr_dir,'/year2018/html'))
states2018 <- sapply(files2018, htmlParse)

{
  pres_tables_al_de <- xpathSApply(doc = states2018$`1.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_fl_ky <- xpathSApply(doc = states2018$`2.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_me_ne <- xpathSApply(doc = states2018$`3.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_nv_or <- xpathSApply(doc = states2018$`4.html`, path ="//table[@dir='ltr']//child::table")
  pres_tables_pa_wi <- xpathSApply(doc = states2018$`5.html`, path ="//table[@dir='ltr']//child::table")
}

# write txt
setwd(paste0(scr_dir,'/year2018/txt'))

{
  sink("Alabama_Delaware2018.txt")
  print(pres_tables_al_de)
  sink()
  sink("Florida_Kentucky2018.txt")
  print(pres_tables_fl_ky)
  sink()  
  sink("Maine_Nebraska2018.txt")
  print(pres_tables_me_ne)
  sink()
  sink("Nevada_Oregon2018.txt")
  print(pres_tables_nv_or)
  sink()
  sink("Pennsylvania_Wisconsin2018.txt")
  print(pres_tables_pa_wi)
  sink()
}

rm(list=ls(pattern="^pres_"))


