#-------------------------------------------------------------------------------
#
# Process script: Convert html to txt for presidential polls from 2000 to 2020 
# Author: Sina Chen
# Source: www.pollingreport.com 
#
#-------------------------------------------------------------------------------


# Libraries ---------------------------------------------------------------

library(XML)
library(stringr)
library(xml2)
library(rvest)
library(dplyr)
library(readr)
library(tidyr)
library(tibble)

# working directory
scr_dir <- "your_wd"

#-------------------------------------------------------------------------------


# 2000 --------------------------------------------------------------------

# read html
setwd(paste0(scr_dir,'/year2000/html'))
files2000 <- dir(paste0(scr_dir,'/year2000/html'))
states2000 <- sapply(files2000, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2000$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2]) and not(.//hr)]")
  pres_tables_az <- xpathSApply(doc = states2000$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ar <- xpathSApply(doc = states2000$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_ca <- xpathSApply(doc = states2000$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_co <- xpathSApply(doc = states2000$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2]) and not(.//hr)]")
  pres_tables_ct <- xpathSApply(doc = states2000$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_de <- xpathSApply(doc = states2000$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_fl <- xpathSApply(doc = states2000$`8.html`, path ="//table[@dir='ltr']//child::table[position()<=18 and not(position()<=6)]")
  pres_tables_ga <- xpathSApply(doc = states2000$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::p[2]) and not(.//hr)]")
  pres_tables_hi <- xpathSApply(doc = states2000$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_id <- xpathSApply(doc = states2000$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2])]")
  pres_tables_il <- xpathSApply(doc = states2000$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_in <- xpathSApply(doc = states2000$`13.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2]) and not(.//hr)]")
  pres_tables_io <- xpathSApply(doc = states2000$`14.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2]) and not(.//hr)]")
  pres_tables_ks <- xpathSApply(doc = states2000$`15.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::p[2])]")
  pres_tables_ky <- xpathSApply(doc = states2000$`16.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2])]")
  pres_tables_la <- xpathSApply(doc = states2000$`17.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_me <- xpathSApply(doc = states2000$`18.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::p[2])]")
  pres_tables_md <- xpathSApply(doc = states2000$`19.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::p[2])]")
  pres_tables_ma <- xpathSApply(doc = states2000$`20.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::p[2]) and not(.//hr)]")
  pres_tables_mi <- xpathSApply(doc = states2000$`21.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_mn <- xpathSApply(doc = states2000$`22.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(position()=4) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ms <- xpathSApply(doc = states2000$`23.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_mo <- xpathSApply(doc = states2000$`24.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_mt <- xpathSApply(doc = states2000$`25.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_ne <- xpathSApply(doc = states2000$`26.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_nv <- xpathSApply(doc = states2000$`27.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nh <- xpathSApply(doc = states2000$`28.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_nj <- xpathSApply(doc = states2000$`29.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nm <- xpathSApply(doc = states2000$`30.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ny <- xpathSApply(doc = states2000$`31.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nc <- xpathSApply(doc = states2000$`32.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nd <- xpathSApply(doc = states2000$`33.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_oh <- xpathSApply(doc = states2000$`34.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ok <- xpathSApply(doc = states2000$`35.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_or <- xpathSApply(doc = states2000$`36.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_pa <- xpathSApply(doc = states2000$`37.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ri <- xpathSApply(doc = states2000$`38.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_sc <- xpathSApply(doc = states2000$`39.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_tn <- xpathSApply(doc = states2000$`40.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_tx <- xpathSApply(doc = states2000$`41.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ut <- xpathSApply(doc = states2000$`42.html`, path = "//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_vt <- xpathSApply(doc = states2000$`43.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_va <- xpathSApply(doc = states2000$`44.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_wa <- xpathSApply(doc = states2000$`45.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_wv <- xpathSApply(doc = states2000$`46.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_wi <- xpathSApply(doc = states2000$`47.html`, path ="//table[@dir='ltr']//child::table[not(position()=1) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_wy <- xpathSApply(doc = states2000$`48.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)]")
}

# convert to txt (rvest not applicable to lists and document class = externalptr)
dir.create(paste0(scr_dir,'/year2000/txt/'), recursive = T)
setwd(paste0(scr_dir,'/year2000/txt'))

{
  sink("Alabama2000.txt")
  print(pres_tables_al)
  sink()
  sink("Arizona2000.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2000.txt")
  print(pres_tables_ar)
  sink()
  sink("California2000.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2000.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2000.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2000.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2000.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2000.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii2000.txt")
  print(pres_tables_hi)
  sink()
  sink("Idaho2000.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2000.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2000.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2000.txt")
  print(pres_tables_io)
  sink()
  sink("Kansas2000.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2000.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2000.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2000.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2000.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2000.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2000.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2000.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2000.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2000.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2000.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2000.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2000.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2000.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2000.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2000.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2000.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2000.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2000.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2000.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2000.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2000.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2000.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2000.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2000.txt")
  print(pres_tables_sc)
  sink()
  sink("Tennessee2000.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2000.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2000.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2000.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2000.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2000.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2000.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2000.txt")
  print(pres_tables_wi)
  sink()
  sink("Wyoming2000.txt")
  print(pres_tables_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))



# 2004 --------------------------------------------------------------------

# read html
setwd(paste0(scr_dir,'/year2004/html'))
files2004 <- dir(paste0(scr_dir,'/year2004/html'))
states2004 <- sapply(files2004, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2004$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::p[1]) and not(.//hr)]")
  pres_tables_ak <- xpathSApply(doc = states2004$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::p[1]) ]")
  pres_tables_az <- xpathSApply(doc = states2004$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ar <- xpathSApply(doc = states2004$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr) ]")
  pres_tables_ca <- xpathSApply(doc = states2004$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_co <- xpathSApply(doc = states2004$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ct <- xpathSApply(doc = states2004$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_de <- xpathSApply(doc = states2004$`8.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_dc <- xpathSApply(doc = states2004$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)and not(.//hr)]")
  pres_tables_fl <- xpathSApply(doc = states2004$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)and not(.//hr)]")
  pres_tables_ga <- xpathSApply(doc = states2004$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_hi <- xpathSApply(doc = states2004$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_id <- xpathSApply(doc = states2004$`13.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_il <- xpathSApply(doc = states2004$`14.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(position()>19) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_il1 <- xpathSApply(doc = states2004$`14.html`, path ="//table[@dir='ltr']//child::font/table ")
  pres_tables_il <- c(pres_tables_il1[1],pres_tables_il[1:17])
  pres_tables_in <- xpathSApply(doc = states2004$`15.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_io <- xpathSApply(doc = states2004$`16.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ks <- xpathSApply(doc = states2004$`17.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_ky <- xpathSApply(doc = states2004$`18.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_la <- xpathSApply(doc = states2004$`19.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_me <- xpathSApply(doc = states2004$`20.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_md <- xpathSApply(doc = states2004$`21.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ma <- xpathSApply(doc = states2004$`22.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2)  and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_mi <- xpathSApply(doc = states2004$`23.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_mn <- xpathSApply(doc = states2004$`24.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2)  and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ms <- xpathSApply(doc = states2004$`25.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(.//hr)]")
  pres_tables_mo <- xpathSApply(doc = states2004$`26.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr)and not(.//hr)]")
  pres_tables_mt <- xpathSApply(doc = states2004$`27.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ne <- xpathSApply(doc = states2004$`28.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nv <- xpathSApply(doc = states2004$`29.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr) ]")
  pres_tables_nh <- xpathSApply(doc = states2004$`30.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr)]")
  pres_tables_nj <- xpathSApply(doc = states2004$`31.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nm <- xpathSApply(doc = states2004$`32.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ny <- xpathSApply(doc = states2004$`33.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nc <- xpathSApply(doc = states2004$`34.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_nd <- xpathSApply(doc = states2004$`35.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_oh <- xpathSApply(doc = states2004$`36.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ok <- xpathSApply(doc = states2004$`37.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_or <- xpathSApply(doc = states2004$`38.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_pa <- xpathSApply(doc = states2004$`39.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ri <- xpathSApply(doc = states2004$`40.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_sc <- xpathSApply(doc = states2004$`41.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_sd <- xpathSApply(doc = states2004$`42.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_tn <- xpathSApply(doc = states2004$`43.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_tx <- xpathSApply(doc = states2004$`44.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_ut <- xpathSApply(doc = states2004$`45.html`, path ="//table[@dir='ltr']//child::table[not(position()<=3) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_vt <- xpathSApply(doc = states2004$`46.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_va <- xpathSApply(doc = states2004$`47.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_wa <- xpathSApply(doc = states2004$`48.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_wv <- xpathSApply(doc = states2004$`49.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
  pres_tables_wi <- xpathSApply(doc = states2004$`50.html`, path ="//table[@dir='ltr']//child::table[not(position()<=2) and not(preceding-sibling::table/tr/td/hr) and not(.//hr)]")
}

# convert to txt (rvest not applicable to lists and document class = externalptr)
dir.create(paste0(scr_dir,'/year2004/txt/'), recursive = T)
setwd(paste0(scr_dir,'/year2004/txt'))

{
  sink("Alabama2004.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska2004.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2004.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2004.txt")
  print(pres_tables_ar)
  sink()
  sink("California2004.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2004.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2004.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2004.txt")
  print(pres_tables_de)
  sink()
  sink("DistrictOfColumbia2004.txt")
  print(pres_tables_dc)
  sink()
  sink("Florida2004.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2004.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii2004.txt")
  print(pres_tables_hi)
  sink()
  sink("Idaho2004.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2004.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2004.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2004.txt")
  print(pres_tables_io)
  sink()
  sink("Kansas2004.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2004.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2004.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2004.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2004.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2004.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2004.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2004.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2004.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2004.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2004.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2004.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2004.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2004.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2004.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2004.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2004.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2004.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2004.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2004.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2004.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2004.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2004.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2004.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2004.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2004.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2004.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2004.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2004.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2004.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2004.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2004.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2004.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2004.txt")
  print(pres_tables_wi)
  sink()
}
rm(list=ls(pattern="^pres_"))



# 2008 --------------------------------------------------------------------

# read html
setwd(paste0(scr_dir,'/year2008/html'))
files2008 <- dir(paste0(scr_dir,'/year2008/html'))
states2008 <- sapply(files2008, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2008$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>23)]")
  pres_tables_ak <- xpathSApply(doc = states2008$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>16)]")
  pres_tables_az <- xpathSApply(doc = states2008$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=50) and not(position()>75)]")
  pres_tables_ar <- xpathSApply(doc = states2008$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=87) and not(position()>95)]")
  pres_tables_ca <- xpathSApply(doc = states2008$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) ]")
  pres_tables_co <- xpathSApply(doc = states2008$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>28)]")
  pres_tables_ct <- xpathSApply(doc = states2008$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=59) and not(position()>74)]")
  pres_tables_de <- xpathSApply(doc = states2008$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=85) and not(position()>90)]")
  pres_tables_fl <- xpathSApply(doc = states2008$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5)]")
  pres_tables_ga <- xpathSApply(doc = states2008$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>15)]")
  pres_tables_hi <- xpathSApply(doc = states2008$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>5)]")
  pres_tables_id <- xpathSApply(doc = states2008$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>14)]")
  pres_tables_il <- xpathSApply(doc = states2008$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=27) and not(position()>35)]")
  pres_tables_in <- xpathSApply(doc = states2008$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=65) and not(position()>84)]")
  pres_tables_ia <- xpathSApply(doc = states2008$`8.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>53)]")
  pres_tables_ks <- xpathSApply(doc = states2008$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>9)]")
  pres_tables_ky <- xpathSApply(doc = states2008$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=19) and not(position()>31)]")  
  pres_tables_la <- xpathSApply(doc = states2008$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>11)]")
  pres_tables_me <- xpathSApply(doc = states2008$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>20)]")
  pres_tables_md <- xpathSApply(doc = states2008$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=38) and not(position()>50)]")
  pres_tables_ma <- xpathSApply(doc = states2008$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=60) and not(position()>78)]")
  pres_tables_mi <- xpathSApply(doc = states2008$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>47)]")
  pres_tables_mn <- xpathSApply(doc = states2008$`13.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>25)]")
  pres_tables_ms <- xpathSApply(doc = states2008$`14.html`, path ="//table[@dir='ltr']//child::table[not(position()<=7) and not(position()>13)]")
  pres_tables_mo <- xpathSApply(doc = states2008$`14.html`, path ="//table[@dir='ltr']//child::table[not(position()<=26) and not(position()>39)]")  
  pres_tables_mt <- xpathSApply(doc = states2008$`14.html`, path ="//table[@dir='ltr']//child::table[not(position()<=52) and not(position()>61)]")
  pres_tables_ne <- xpathSApply(doc = states2008$`15.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>8)]")
  pres_tables_nv <- xpathSApply(doc = states2008$`15.html`, path ="//table[@dir='ltr']//child::table[not(position()<=19) and not(position()>41)]")
  pres_tables_nh <- xpathSApply(doc = states2008$`16.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6)]")
  pres_tables_nj <- xpathSApply(doc = states2008$`17.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>41)]")
  pres_tables_nm <- xpathSApply(doc = states2008$`18.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>15)]")
  pres_tables_ny <- xpathSApply(doc = states2008$`19.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>50)]")
  pres_tables_nc <- xpathSApply(doc = states2008$`20.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>38)]")
  pres_tables_nd <- xpathSApply(doc = states2008$`21.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>12)]")
  pres_tables_oh <- xpathSApply(doc = states2008$`22.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>55)]")
  pres_tables_ok <- xpathSApply(doc = states2008$`23.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>16)]")
  pres_tables_or <- xpathSApply(doc = states2008$`23.html`, path ="//table[@dir='ltr']//child::table[not(position()<=25) and not(position()>39)]")
  pres_tables_pa <- xpathSApply(doc = states2008$`24.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6)]")
  pres_tables_ri <- xpathSApply(doc = states2008$`25.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>16)]")
  pres_tables_sc <- xpathSApply(doc = states2008$`26.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>41)]")
  pres_tables_sd <- xpathSApply(doc = states2008$`26.html`, path ="//table[@dir='ltr']//child::table[not(position()<=48) and not(position()>54)]")
  pres_tables_tn <- xpathSApply(doc = states2008$`27.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>20)]")
  pres_tables_tx <- xpathSApply(doc = states2008$`28.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>25)]")
  pres_tables_ut <- xpathSApply(doc = states2008$`29.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>16)]")
  pres_tables_vt <- xpathSApply(doc = states2008$`29.html`, path ="//table[@dir='ltr']//child::table[not(position()<=25) and not(position()>33)]")
  pres_tables_va <- xpathSApply(doc = states2008$`29.html`, path ="//table[@dir='ltr']//child::table[not(position()<=42) and not(position()>68)]")
  pres_tables_wa <- xpathSApply(doc = states2008$`30.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>20)]")
  pres_tables_wv <- xpathSApply(doc = states2008$`30.html`, path ="//table[@dir='ltr']//child::table[not(position()<=37) and not(position()>48)]")
  pres_tables_wi <- xpathSApply(doc = states2008$`31.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>31)]")
  pres_tables_wy <- xpathSApply(doc = states2008$`31.html`, path ="//table[@dir='ltr']//child::table[not(position()<=36) and not(position()>42)]")
}

# convert to txt (rvest not applicable to lists and document class = externalptr)
dir.create(paste0(scr_dir,'/year2008/txt/'), recursive = T)
setwd(paste0(scr_dir,'/year2008/txt'))

{
  sink("Alabama2008.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska2008.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2008.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2008.txt")
  print(pres_tables_ar)
  sink()
  sink("California2008.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2008.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2008.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2008.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2008.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2008.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii2008.txt")
  print(pres_tables_hi)
  sink()
  sink("Idaho2008.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2008.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2008.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2008.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas2008.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2008.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2008.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2008.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2008.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2008.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2008.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2008.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2008.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2008.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2008.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2008.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2008.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2008.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2008.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2008.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2008.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2008.txt")
  print(pres_tables_nc)
  sink()
  sink("NorthDakota2008.txt")
  print(pres_tables_nd)
  sink()
  sink("Ohio2008.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2008.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2008.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2008.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2008.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2008.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2008.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2008.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2008.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2008.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2008.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2008.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2008.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2008.txt")
  print(pres_tables_wv)
  sink()
  sink("Wyoming2008.txt")
  print(pres_tables_wy)
  sink()
  sink("Wisconsin2008.txt")
  print(pres_tables_wi)
  sink()
}

rm(list=ls(pattern="^pres_"))



# 2012 --------------------------------------------------------------------

# read html
setwd(paste0(scr_dir,'/year2012/html'))
files2012 <- dir(paste0(scr_dir,'/year2012/html'))
states2012 <- sapply(files2012, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2012$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>16)]")
  pres_tables_ak <- xpathSApply(doc = states2012$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=21) and not(position()>28)]")
  pres_tables_az <- xpathSApply(doc = states2012$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=33) and not(position()>45)]")
  pres_tables_ar <- xpathSApply(doc = states2012$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=66) and not(position()>70)]")
  pres_tables_ca <- xpathSApply(doc = states2012$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>25)]")
  pres_tables_co <- xpathSApply(doc = states2012$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>18)]")
  pres_tables_ct <- xpathSApply(doc = states2012$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=25) and not(position()>34)]")
  pres_tables_de <- xpathSApply(doc = states2012$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=54) and not(position()>57)]")
  pres_tables_fl <- xpathSApply(doc = states2012$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5)]")
  pres_tables_ga <- xpathSApply(doc = states2012$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=6) and not(position()>11)]")
  pres_tables_hi <- xpathSApply(doc = states2012$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=16) and not(position()>17)]")
  pres_tables_id <- xpathSApply(doc = states2012$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=37) and not(position()>39)]")
  pres_tables_il <- xpathSApply(doc = states2012$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=42) and not(position()>50)]")
  pres_tables_in <- xpathSApply(doc = states2012$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=78) and not(position()>85)]")
  pres_tables_ia <- xpathSApply(doc = states2012$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>42)]")
  pres_tables_ks <- xpathSApply(doc = states2012$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=49) and not(position()>50)]")
  pres_tables_ky <- xpathSApply(doc = states2012$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=53) and not(position()>56)]")  
  pres_tables_la <- xpathSApply(doc = states2012$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=62)]")
  pres_tables_me <- xpathSApply(doc = states2012$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>14)]")
  pres_tables_md <- xpathSApply(doc = states2012$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=30) and not(position()>37)]")
  pres_tables_ma <- xpathSApply(doc = states2012$`8.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>26)]")
  pres_tables_mi <- xpathSApply(doc = states2012$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>29)]")
  pres_tables_mn <- xpathSApply(doc = states2012$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=54) and not(position()>61)]")
  pres_tables_ms <- xpathSApply(doc = states2012$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>9)]")
  pres_tables_mo <- xpathSApply(doc = states2012$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=12) and not(position()>17)]")  
  pres_tables_mt <- xpathSApply(doc = states2012$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=35) and not(position()>38)]")
  pres_tables_ne <- xpathSApply(doc = states2012$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=63) and not(position()>67)]")
  pres_tables_nv <- xpathSApply(doc = states2012$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>23)]")
  pres_tables_nh <- xpathSApply(doc = states2012$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5)]")
  pres_tables_nj <- xpathSApply(doc = states2012$`13.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>32)]")
  pres_tables_nm <- xpathSApply(doc = states2012$`13.html`, path ="//table[@dir='ltr']//child::table[not(position()<=61) and not(position()>66)]")
  pres_tables_ny <- xpathSApply(doc = states2012$`14.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8)]")
  pres_tables_nc <- xpathSApply(doc = states2012$`15.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8)]")
  pres_tables_oh <- xpathSApply(doc = states2012$`16.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>51)]")
  pres_tables_ok <- xpathSApply(doc = states2012$`16.html`, path ="//table[@dir='ltr']//child::table[not(position()<=78) and not(position()>85)]")
  pres_tables_or <- xpathSApply(doc = states2012$`16.html`, path ="//table[@dir='ltr']//child::table[not(position()<=93) and not(position()>97)]")
  pres_tables_pa <- xpathSApply(doc = states2012$`17.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>43)]")
  pres_tables_ri <- xpathSApply(doc = states2012$`18.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>12)]")
  pres_tables_sc <- xpathSApply(doc = states2012$`18.html`, path ="//table[@dir='ltr']//child::table[not(position()<=31) and not(position()>46)]")
  pres_tables_sd <- xpathSApply(doc = states2012$`18.html`, path ="//table[@dir='ltr']//child::table[not(position()<=49) and not(position()>50)]")
  pres_tables_tn <- xpathSApply(doc = states2012$`19.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>19)]")
  pres_tables_tx <- xpathSApply(doc = states2012$`19.html`, path ="//table[@dir='ltr']//child::table[not(position()<=29) and not(position()>36)]")
  pres_tables_ut <- xpathSApply(doc = states2012$`20.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>17)]")
  pres_tables_vt <- xpathSApply(doc = states2012$`20.html`, path ="//table[@dir='ltr']//child::table[not(position()<=51) and not(position()>53)]")
  pres_tables_va <- xpathSApply(doc = states2012$`21.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>41)]")
  pres_tables_wa <- xpathSApply(doc = states2012$`22.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>17)]")
  pres_tables_wv <- xpathSApply(doc = states2012$`22.html`, path ="//table[@dir='ltr']//child::table[not(position()<=45) and not(position()>49)]")
  pres_tables_wi <- xpathSApply(doc = states2012$`23.html`, path ="//table[@dir='ltr']//child::table[not(position()<=8) and not(position()>27)]")
}

# convert to txt (rvest not applicable to lists and document class = externalptr)
dir.create(paste0(scr_dir,'/year2012/txt/'), recursive = T)
setwd(paste0(scr_dir,'/year2012/txt'))

{
  sink("Alabama2012.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska2012.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2012.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2012.txt")
  print(pres_tables_ar)
  sink()
  sink("California2012.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2012.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2012.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2012.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2012.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2012.txt")
  print(pres_tables_ga)
  sink()
  sink("Hawaii2012.txt")
  print(pres_tables_hi)
  sink()
  sink("Idaho2012.txt")
  print(pres_tables_id)
  sink()
  sink("Illinois2012.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2012.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2012.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas2012.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2012.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2012.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2012.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2012.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2012.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2012.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2012.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2012.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2012.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2012.txt")
  print(pres_tables_mt)
  sink()
  sink("Nebraska2012.txt")
  print(pres_tables_ne)
  sink()
  sink("Nevada2012.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2012.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2012.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2012.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2012.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthCarolina2012.txt")
  print(pres_tables_nc)
  sink()
  sink("Ohio2012.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2012.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2012.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2012.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2012.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2012.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2012.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2012.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2012.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2012.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2012.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2012.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2012.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2012.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2012.txt")
  print(pres_tables_wi)
  sink()
}

rm(list=ls(pattern="^pres_"))


# 2016 --------------------------------------------------------------------

# read html
setwd(paste0(scr_dir,'/year2016/html'))
files2016 <- dir(paste0(scr_dir,'/year2016/html'))
states2016 <- sapply(files2016, htmlParse)

{
  pres_tables_ak <- xpathSApply(doc = states2016$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=10) and not(position()>17)]")
  pres_tables_az <- xpathSApply(doc = states2016$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=28) and not(position()>39)]")
  pres_tables_ar <- xpathSApply(doc = states2016$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=55) and not(position()>62)]")
  pres_tables_ca <- xpathSApply(doc = states2016$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=68) and not(position()>90)]")
  pres_tables_co <- xpathSApply(doc = states2016$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=126) and not(position()>147)]")
  pres_tables_ct <- xpathSApply(doc = states2016$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>8)]")
  pres_tables_de <- xpathSApply(doc = states2016$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=15) and not(position()>17)]")
  pres_tables_fl <- xpathSApply(doc = states2016$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>60)]")
  pres_tables_ga <- xpathSApply(doc = states2016$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=113) and not(position()>124)]")
  pres_tables_il <- xpathSApply(doc = states2016$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>11)]")
  pres_tables_in <- xpathSApply(doc = states2016$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=31) and not(position()>42)]")
  pres_tables_ia <- xpathSApply(doc = states2016$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>80)]")
  pres_tables_ks <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>11)]")
  pres_tables_ky <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=16) and not(position()>24)]")  
  pres_tables_la <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=31)and not(position()>41)]")
  pres_tables_me <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=56) and not(position()>61)]")
  pres_tables_md <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=70) and not(position()>90)]")
  pres_tables_ma <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=120) and not(position()>138)]")
  pres_tables_mi <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=144) and not(position()>169)]")
  pres_tables_mn <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=172) and not(position()>177)]")
  pres_tables_ms <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=186) and not(position()>187)]")
  pres_tables_mo <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=190) and not(position()>196)]")  
  pres_tables_mt <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=214) and not(position()>215)]")
  pres_tables_nv <- xpathSApply(doc = states2016$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=224) and not(position()>237)]")
  pres_tables_nh <- xpathSApply(doc = states2016$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>78)]")
  pres_tables_nj <- xpathSApply(doc = states2016$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=133) and not(position()>165)]")
  pres_tables_nm <- xpathSApply(doc = states2016$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=168) and not(position()>171)]")
  pres_tables_ny <- xpathSApply(doc = states2016$`8.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>31)]")
  pres_tables_nc <- xpathSApply(doc = states2016$`8.html`, path ="//table[@dir='ltr']//child::table[not(position()<=54) and not(position()>90)]")
  pres_tables_nd <- xpathSApply(doc = states2016$`8.html`, path ="//table[@dir='ltr']//child::table[not(position()<=142) ]")
  pres_tables_oh <- xpathSApply(doc = states2016$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>43)]")
  pres_tables_ok <- xpathSApply(doc = states2016$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=64) and not(position()>72)]")
  pres_tables_or <- xpathSApply(doc = states2016$`9.html`, path ="//table[@dir='ltr']//child::table[not(position()<=75) and not(position()>82)]")
  pres_tables_pa <- xpathSApply(doc = states2016$`10.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>47)]")
  pres_tables_ri <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>8)]")
  pres_tables_sc <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=11) and not(position()>35)]")
  pres_tables_sd <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=43) and not(position()>46)]")
  pres_tables_tn <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=53) and not(position()>62)]")
  pres_tables_tx <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=67) and not(position()>76)]")
  pres_tables_ut <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=81) and not(position()>86)]")
  pres_tables_vt <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=99) and not(position()>102)]")
  pres_tables_va <- xpathSApply(doc = states2016$`11.html`, path ="//table[@dir='ltr']//child::table[not(position()<=117) and not(position()>161)]")
  pres_tables_wa <- xpathSApply(doc = states2016$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=4) and not(position()>6)]")
  pres_tables_wv <- xpathSApply(doc = states2016$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=21) and not(position()>22)]")
  pres_tables_wi <- xpathSApply(doc = states2016$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=29) and not(position()>54)]")
  pres_tables_wy <- xpathSApply(doc = states2016$`12.html`, path ="//table[@dir='ltr']//child::table[not(position()<=74) and not(position()>76)]")
}

# convert to txt (rvest not applicable to lists and document class = externalptr)
dir.create(paste0(scr_dir,'/year2016/txt/'), recursive = T)
setwd(paste0(scr_dir,'/year2016/txt'))

{
  sink("Alaska2016.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2016.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2016.txt")
  print(pres_tables_ar)
  sink()
  sink("California2016.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2016.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2016.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2016.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2016.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2016.txt")
  print(pres_tables_ga)
  sink()
  sink("Illinois2016.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2016.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2016.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas2016.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2016.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2016.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2016.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2016.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2016.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2016.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2016.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2016.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2016.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2016.txt")
  print(pres_tables_mt)
  sink()
  sink("Nevada2016.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2016.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2016.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2016.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2016.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthDakota2016.txt")
  print(pres_tables_nd)
  sink()
  sink("NorthCarolina2016.txt")
  print(pres_tables_nc)
  sink()
  sink("Ohio2016.txt")
  print(pres_tables_oh)
  sink()
  sink("Oklahoma2016.txt")
  print(pres_tables_ok)
  sink()
  sink("Oregon2016.txt")
  print(pres_tables_or)
  sink()
  sink("Pennsylvania2016.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2016.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2016.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2016.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2016.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2016.txt")
  print(pres_tables_tx)
  sink()
  sink("Utah2016.txt")
  print(pres_tables_ut)
  sink()
  sink("Vermont2016.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2016.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2016.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2016.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2016.txt")
  print(pres_tables_wi)
  sink()
  sink("Wyoming2016.txt")
  print(pres_tables_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))


# 2020 --------------------------------------------------------------------

# read html
setwd(paste0(scr_dir,'/year2020/html'))
files2020 <- dir(paste0(scr_dir,'/year2020/html'))
states2020 <- sapply(files2020, htmlParse)

{
  pres_tables_al <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>10)]")
  pres_tables_ak <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=28) and not(position()>31)]")
  pres_tables_az <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=39) and not(position()>63)]")
  pres_tables_ar <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=70) and not(position()>71)]")
  pres_tables_ca <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=80) and not(position()>100)]")
  pres_tables_co <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=114) and not(position()>123)]")
  pres_tables_ct <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=138) and not(position()>140)]")
  pres_tables_de <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=143) and not(position()>145)]")
  pres_tables_fl <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=157) and not(position()>199)]")
  pres_tables_ga <- xpathSApply(doc = states2020$`1.html`, path ="//table[@dir='ltr']//child::table[not(position()<=206) and not(position()>227)]")
  pres_tables_il <- xpathSApply(doc = states2020$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>7)]")
  pres_tables_in <- xpathSApply(doc = states2020$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=12) and not(position()>17)]")
  pres_tables_ia <- xpathSApply(doc = states2020$`2.html`, path ="//table[@dir='ltr']//child::table[not(position()<=24) and not(position()>57)]")
  pres_tables_ks <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>7)]")
  pres_tables_ky <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=15) and not(position()>20)]")  
  pres_tables_la <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=32)and not(position()>36)]")
  pres_tables_me <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=41) and not(position()>47)]")
  pres_tables_md <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=57) and not(position()>71)]")
  pres_tables_ma <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=74) and not(position()>86)]")
  pres_tables_mi <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=97) and not(position()>131)]")
  pres_tables_mn <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=159) and not(position()>171)]")
  pres_tables_ms <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=187) and not(position()>192)]")
  pres_tables_mo <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=202) and not(position()>207)]") 
  pres_tables_mt <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=214) and not(position()>218)]")
  pres_tables_nv <- xpathSApply(doc = states2020$`3.html`, path ="//table[@dir='ltr']//child::table[not(position()<=241) and not(position()>254)]")
  pres_tables_nh <- xpathSApply(doc = states2020$`4.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>40)]")
  pres_tables_nj <- xpathSApply(doc = states2020$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>21)]")
  pres_tables_nm <- xpathSApply(doc = states2020$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=42) and not(position()>45)]")
  pres_tables_ny <- xpathSApply(doc = states2020$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=56) and not(position()>70)]")
  pres_tables_nc <- xpathSApply(doc = states2020$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=83) and not(position()>115)]")
  pres_tables_nd <- xpathSApply(doc = states2020$`5.html`, path ="//table[@dir='ltr']//child::table[not(position()<=162) and not(position()>168)]")
  pres_tables_oh <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>17)]") 
  pres_tables_pa <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=35) and not(position()>71)]")
  pres_tables_pa <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=35) and not(position()>71)]")
  pres_tables_ri <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=82) and not(position()>87)]")
  pres_tables_sc <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=93) and not(position()>110)]")
  pres_tables_sd <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=126) and not(position()>128)]")
  pres_tables_tn <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=131) and not(position()>142)]")
  pres_tables_tx <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=152) and not(position()>165)]")
  pres_tables_vt <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=196) and not(position()>198)]")
  pres_tables_va <- xpathSApply(doc = states2020$`6.html`, path ="//table[@dir='ltr']//child::table[not(position()<=205) and not(position()>231)]")
  pres_tables_wa <- xpathSApply(doc = states2020$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=5) and not(position()>7)]")
  pres_tables_wv <- xpathSApply(doc = states2020$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=17) and not(position()>21)]")
  pres_tables_wi <- xpathSApply(doc = states2020$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=30) and not(position()>63)]")
  pres_tables_wy <- xpathSApply(doc = states2020$`7.html`, path ="//table[@dir='ltr']//child::table[not(position()<=66) and not(position()>67)]")

}

# convert to txt (rvest not applicable to lists and document class = externalptr)
dir.create(paste0(scr_dir,'/year2020/txt/'), recursive = T)
setwd(paste0(scr_dir,'/year2020/txt'))

{
  sink("Alabama2020.txt")
  print(pres_tables_al)
  sink()
  sink("Alaska2020.txt")
  print(pres_tables_ak)
  sink()
  sink("Arizona2020.txt")
  print(pres_tables_az)
  sink()
  sink("Arkansas2020.txt")
  print(pres_tables_ar)
  sink()
  sink("California2020.txt")
  print(pres_tables_ca)
  sink()
  sink("Colorado2020.txt")
  print(pres_tables_co)
  sink()
  sink("Connecticut2020.txt")
  print(pres_tables_ct)
  sink()
  sink("Delaware2020.txt")
  print(pres_tables_de)
  sink()
  sink("Florida2020.txt")
  print(pres_tables_fl)
  sink()
  sink("Georgia2020.txt")
  print(pres_tables_ga)
  sink()
  sink("Illinois2020.txt")
  print(pres_tables_il)
  sink()
  sink("Indiana2020.txt")
  print(pres_tables_in)
  sink()
  sink("Iowa2020.txt")
  print(pres_tables_ia)
  sink()
  sink("Kansas2020.txt")
  print(pres_tables_ks)
  sink()
  sink("Kentucky2020.txt")
  print(pres_tables_ky)
  sink()
  sink("Louisiana2020.txt")
  print(pres_tables_la)
  sink()
  sink("Maine2020.txt")
  print(pres_tables_me)
  sink()
  sink("Maryland2020.txt")
  print(pres_tables_md)
  sink()
  sink("Massachusetts2020.txt")
  print(pres_tables_ma)
  sink()
  sink("Michigan2020.txt")
  print(pres_tables_mi)
  sink()
  sink("Minnesota2020.txt")
  print(pres_tables_mn)
  sink()
  sink("Mississippi2020.txt")
  print(pres_tables_ms)
  sink()
  sink("Missouri2020.txt")
  print(pres_tables_mo)
  sink()
  sink("Montana2020.txt")
  print(pres_tables_mt)
  sink()
  sink("Nevada2020.txt")
  print(pres_tables_nv)
  sink()
  sink("NewHampshire2020.txt")
  print(pres_tables_nh)
  sink()
  sink("NewJersey2020.txt")
  print(pres_tables_nj)
  sink()
  sink("NewMexico2020.txt")
  print(pres_tables_nm)
  sink()
  sink("NewYork2020.txt")
  print(pres_tables_ny)
  sink()
  sink("NorthDakota2020.txt")
  print(pres_tables_nd)
  sink()
  sink("NorthCarolina2020.txt")
  print(pres_tables_nc)
  sink()
  sink("Ohio2020.txt")
  print(pres_tables_oh)
  sink()
  sink("Pennsylvania2020.txt")
  print(pres_tables_pa)
  sink()
  sink("RhodeIsland2020.txt")
  print(pres_tables_ri)
  sink()
  sink("SouthCarolina2020.txt")
  print(pres_tables_sc)
  sink()
  sink("SouthDakota2020.txt")
  print(pres_tables_sd)
  sink()
  sink("Tennessee2020.txt")
  print(pres_tables_tn)
  sink()
  sink("Texas2020.txt")
  print(pres_tables_tx)
  sink()
  sink("Vermont2020.txt")
  print(pres_tables_vt)
  sink()
  sink("Virginia2020.txt")
  print(pres_tables_va)
  sink()
  sink("Washington2020.txt")
  print(pres_tables_wa)
  sink()
  sink("WestVirginia2020.txt")
  print(pres_tables_wv)
  sink()
  sink("Wisconsin2020.txt")
  print(pres_tables_wi)
  sink()
  sink("Wyoming2020.txt")
  print(pres_tables_wy)
  sink()
}

rm(list=ls(pattern="^pres_"))
